import type {
  Banner,
  BlogPost,
  CategoryTile,
  NavMegaColumn,
  Product,
} from "./types";

const CLOTHES = ["S", "M", "L", "XL"];
const SHOES = ["7", "8", "9", "10", "11"];

export const products: Product[] = [
  {
    _type: "product",
    _id: "baby-fabric-shoes",
    slug: "baby-fabric-shoes",
    title: "baby fabric shoes",
    category: "Clothes",
    parentCategory: "clothes",
    price: 4,
    compareAt: 5,
    images: ["/images/products/1.jpg"],
    rating: 4,
    stock: 42,
    description:
      "Soft fabric first-walkers with a flexible sole and gentle elastic cuff. Lightweight enough for all-day play, with a roomy toe box that lets little feet move naturally.",
    details: ["Cotton-blend upper", "Non-slip sole", "Machine washable"],
    sections: ["bestsellers"],
    sizes: ["4", "5", "6", "7"],
    colors: ["Mint", "Ivory"],
  },
  {
    _type: "product",
    _id: "mens-hoodies-t-shirt",
    slug: "mens-hoodies-t-shirt",
    title: "men's hoodies t-shirt",
    category: "Clothes",
    parentCategory: "clothes",
    price: 7,
    compareAt: 17,
    images: ["/images/products/2.jpg"],
    rating: 4,
    stock: 80,
    description:
      "A relaxed hoodie-tee hybrid in brushed cotton. Drop shoulders, a roomy hood, and a clean hem that layers over jeans or shorts without extra bulk.",
    details: ["Brushed cotton", "Kangaroo pocket", "Regular fit"],
    badge: "sale",
    sections: ["bestsellers"],
    sizes: CLOTHES,
    colors: ["Grey", "Black"],
  },
  {
    _type: "product",
    _id: "girls-t-shirt",
    slug: "girls-t-shirt",
    title: "girls t-shirt",
    category: "Clothes",
    parentCategory: "clothes",
    price: 3,
    compareAt: 5,
    images: ["/images/products/3.jpg"],
    rating: 5,
    stock: 64,
    description:
      "Everyday crew-neck tee in a soft jersey knit. Breathable, colorfast, and cut with a little extra length so it stays tucked during play.",
    details: ["Jersey knit", "Crew neck", "Pre-shrunk"],
    sections: ["bestsellers"],
    sizes: ["4Y", "6Y", "8Y", "10Y"],
    colors: ["Pink", "White"],
  },
  {
    _type: "product",
    _id: "woolen-hat-for-men",
    slug: "woolen-hat-for-men",
    title: "woolen hat for men",
    category: "Mens Fashion",
    parentCategory: "clothes",
    price: 12,
    compareAt: 15,
    images: ["/images/products/4.jpg"],
    rating: 4,
    stock: 39,
    description:
      "Rib-knit wool beanie with a folded cuff. Holds its shape, stays warm without itching, and packs flat in a coat pocket.",
    details: ["Wool blend", "Double-layer cuff", "One size"],
    sections: ["bestsellers"],
    colors: ["Camel", "Charcoal"],
  },
  {
    _type: "product",
    _id: "relaxed-short-full-sleeve-t-shirt",
    slug: "relaxed-short-full-sleeve-t-shirt",
    title: "Relaxed Short full Sleeve T-Shirt",
    category: "Clothes",
    parentCategory: "clothes",
    price: 45,
    compareAt: 12,
    images: ["/images/products/clothes-1.jpg"],
    rating: 4,
    stock: 35,
    description:
      "Boxy short-sleeve knit with a dropped shoulder and a slightly cropped hem. The cotton slub yarn gives it a lived-in texture from day one.",
    details: ["100% cotton slub", "Relaxed fit", "Garment washed"],
    sections: ["new-arrivals"],
    sizes: CLOTHES,
    colors: ["Olive", "Sand"],
  },
  {
    _type: "product",
    _id: "girls-pnk-embro-design-top",
    slug: "girls-pnk-embro-design-top",
    title: "Girls pnk Embro design Top",
    category: "Clothes",
    parentCategory: "clothes",
    price: 61,
    compareAt: 9,
    images: ["/images/products/clothes-2.jpg"],
    rating: 5,
    stock: 22,
    description:
      "Blush pink blouse with tonal floral embroidery across the yoke. Lightweight viscose drape, covered buttons, and a tie at the neck.",
    details: ["Embroidered viscose", "Tie neck", "Lined yoke"],
    sections: ["new-arrivals"],
    sizes: CLOTHES,
    colors: ["Blush"],
  },
  {
    _type: "product",
    _id: "black-floral-wrap-midi-skirt",
    slug: "black-floral-wrap-midi-skirt",
    title: "Black Floral Wrap Midi Skirt",
    category: "skirt",
    parentCategory: "clothes",
    price: 25,
    compareAt: 35,
    images: ["/images/products/clothes-3.jpg", "/images/products/clothes-4.jpg"],
    rating: 4,
    stock: 28,
    description:
      "Wrap midi in a black floral print with a self-tie waist. Moves easily, pairs with a tucked tee or a knit, and sits just below the knee.",
    details: ["Wrap silhouette", "Self-tie waist", "Midi length"],
    badge: "new",
    sections: ["new-arrivals", "grid"],
    sizes: CLOTHES,
    colors: ["Black floral"],
  },
  {
    _type: "product",
    _id: "pure-garment-dyed-cotton-shirt",
    slug: "pure-garment-dyed-cotton-shirt",
    title: "Pure Garment Dyed Cotton Shirt",
    category: "shirt",
    parentCategory: "clothes",
    price: 45,
    compareAt: 56,
    images: ["/images/products/shirt-1.jpg", "/images/products/shirt-2.jpg"],
    rating: 4,
    stock: 40,
    description:
      "Garment-dyed oxford with a soft, broken-in hand. Button-down collar, single chest pocket, and a slightly curved hem that works tucked or open.",
    details: ["Garment dyed cotton", "Button-down collar", "Chest pocket"],
    badge: "sale",
    sections: ["new-arrivals", "grid"],
    sizes: CLOTHES,
    colors: ["Sky", "White"],
  },
  {
    _type: "product",
    _id: "men-yarn-fleece-full-zip-jacket",
    slug: "men-yarn-fleece-full-zip-jacket",
    title: "MEN Yarn Fleece Full-Zip Jacket",
    category: "Jacket",
    parentCategory: "clothes",
    price: 58,
    compareAt: 65,
    images: ["/images/products/jacket-5.jpg", "/images/products/jacket-6.jpg"],
    rating: 4,
    stock: 33,
    description:
      "Full-zip fleece in a heathered yarn knit. Stand collar, zip hand pockets, and a smooth lining that slides over a shirt without clinging.",
    details: ["Yarn fleece", "Full zip", "Two hand pockets"],
    sections: ["new-arrivals", "grid"],
    sizes: CLOTHES,
    colors: ["Navy", "Grey"],
  },
  {
    _type: "product",
    _id: "mens-winter-leathers-jackets",
    slug: "mens-winter-leathers-jackets",
    title: "Mens Winter Leathers Jackets",
    category: "jacket",
    parentCategory: "clothes",
    price: 48,
    compareAt: 75,
    images: ["/images/products/jacket-3.jpg", "/images/products/jacket-4.jpg"],
    rating: 3,
    stock: 18,
    description:
      "A cropped winter leather jacket with a stand collar, zip cuffs, and a quilted lining. Structured through the shoulder, easy through the body.",
    details: ["Genuine leather", "Quilted lining", "Zip cuffs"],
    badge: "15%",
    sections: ["new-arrivals", "grid"],
    sizes: CLOTHES,
    colors: ["Brown", "Black"],
  },
  {
    _type: "product",
    _id: "mens-winter-leather-jacket-classic",
    slug: "mens-winter-leather-jacket-classic",
    title: "Mens Winter Leathers Jackets",
    category: "jacket",
    parentCategory: "clothes",
    price: 32,
    compareAt: 45,
    images: ["/images/products/jacket-1.jpg", "/images/products/jacket-2.jpg"],
    rating: 4,
    stock: 24,
    description:
      "Classic racer leather with a snap collar and welt pockets. A lighter winter layer that sits cleanly over knitwear.",
    details: ["Racer cut", "Snap collar", "Welt pockets"],
    badge: "sale",
    sections: ["new-arrivals", "grid"],
    sizes: CLOTHES,
    colors: ["Black"],
  },
  {
    _type: "product",
    _id: "better-basics-french-terry-sweatshorts",
    slug: "better-basics-french-terry-sweatshorts",
    title: "Better Basics French Terry Sweatshorts",
    category: "shorts",
    parentCategory: "clothes",
    price: 78,
    compareAt: 85,
    images: ["/images/products/shorts-1.jpg", "/images/products/shorts-2.jpg"],
    rating: 3,
    stock: 50,
    description:
      "Heavyweight French terry shorts with a drawcord waist and side pockets. The loopback interior stays soft after washing.",
    details: ["French terry", "Drawcord waist", "Side pockets"],
    badge: "sale",
    sections: ["new-arrivals", "grid"],
    sizes: CLOTHES,
    colors: ["Heather grey"],
  },
  {
    _type: "product",
    _id: "running-trekking-shoes-white",
    slug: "running-trekking-shoes-white",
    title: "Running & Trekking Shoes - White",
    category: "Sports",
    parentCategory: "footwear",
    price: 49,
    compareAt: 15,
    images: ["/images/products/sports-1.jpg"],
    rating: 4,
    stock: 45,
    description:
      "Lightweight trail-to-town runner in a white mesh upper. Cushioned midsole, sticky rubber outsole, and a locked-in heel.",
    details: ["Mesh upper", "Cushioned midsole", "Rubber outsole"],
    sections: ["trending"],
    sizes: SHOES,
    colors: ["White"],
  },
  {
    _type: "product",
    _id: "trekking-running-shoes-black",
    slug: "trekking-running-shoes-black",
    title: "Trekking & Running Shoes - black",
    category: "sports",
    parentCategory: "footwear",
    price: 58,
    compareAt: 64,
    images: ["/images/products/sports-2.jpg", "/images/products/sports-4.jpg"],
    rating: 3,
    stock: 36,
    description:
      "All-black trekking runner with a reinforced toe cap and a lugged sole that grips wet rock as easily as pavement.",
    details: ["Reinforced toe", "Lugged sole", "Water-resistant overlay"],
    badge: "sale",
    sections: ["trending", "grid"],
    sizes: SHOES,
    colors: ["Black"],
  },
  {
    _type: "product",
    _id: "womens-party-wear-shoes",
    slug: "womens-party-wear-shoes",
    title: "Womens Party Wear Shoes",
    category: "party wear",
    parentCategory: "footwear",
    price: 25,
    compareAt: 30,
    images: ["/images/products/party-wear-1.jpg", "/images/products/party-wear-2.jpg"],
    rating: 3,
    stock: 20,
    description:
      "Strappy party heels with a stable block heel and a softly padded insole. Dress-ready without the all-night pinch.",
    details: ["Block heel", "Padded insole", "Ankle strap"],
    badge: "sale",
    sections: ["trending", "grid"],
    sizes: SHOES,
    colors: ["Nude", "Black"],
  },
  {
    _type: "product",
    _id: "sports-claw-womens-shoes",
    slug: "sports-claw-womens-shoes",
    title: "Sports Claw Women's Shoes",
    category: "Sports",
    parentCategory: "footwear",
    price: 54,
    compareAt: 65,
    images: ["/images/products/sports-3.jpg"],
    rating: 4,
    stock: 29,
    description:
      "Claw-outsole training shoe built for lateral work. Breathable knit upper with a snug midfoot wrap.",
    details: ["Claw outsole", "Knit upper", "Training last"],
    sections: ["trending"],
    sizes: SHOES,
    colors: ["White/pink"],
  },
  {
    _type: "product",
    _id: "air-trekking-shoes-white",
    slug: "air-trekking-shoes-white",
    title: "Air Trekking Shoes - white",
    category: "Sports",
    parentCategory: "footwear",
    price: 52,
    compareAt: 55,
    images: ["/images/products/sports-6.jpg"],
    rating: 4,
    stock: 31,
    description:
      "Cushioned trekking sneaker with a visible air unit and a bright white leather-mesh mix that wipes clean.",
    details: ["Air cushion", "Leather-mesh mix", "Wipes clean"],
    sections: ["trending"],
    sizes: SHOES,
    colors: ["White"],
  },
  {
    _type: "product",
    _id: "boot-with-suede-detail",
    slug: "boot-with-suede-detail",
    title: "Boot With Suede Detail",
    category: "boots",
    parentCategory: "footwear",
    price: 20,
    compareAt: 30,
    images: ["/images/products/shoe-3.jpg", "/images/products/shoe-4.jpg"],
    rating: 4,
    stock: 16,
    description:
      "Ankle boot with a suede shaft, stacked heel, and a side zip. The round toe keeps it casual enough for denim.",
    details: ["Suede shaft", "Side zip", "Stacked heel"],
    sections: ["trending"],
    sizes: SHOES,
    colors: ["Tan"],
  },
  {
    _type: "product",
    _id: "mens-leather-formal-wear-shoes",
    slug: "mens-leather-formal-wear-shoes",
    title: "Men's Leather Formal Wear shoes",
    category: "formal",
    parentCategory: "footwear",
    price: 50,
    compareAt: 65,
    images: ["/images/products/shoe-1.jpg", "/images/products/shoe-1_1.jpg"],
    rating: 4,
    stock: 27,
    description:
      "Oxford in polished leather with a slim last and a stacked leather sole. The kind of shoe that finishes a suit without looking costume-y.",
    details: ["Polished leather", "Oxford lacing", "Leather sole"],
    sections: ["trending", "grid"],
    sizes: SHOES,
    colors: ["Black", "Cognac"],
  },
  {
    _type: "product",
    _id: "casual-mens-brown-shoes",
    slug: "casual-mens-brown-shoes",
    title: "Casual Men's Brown shoes",
    category: "casual",
    parentCategory: "footwear",
    price: 99,
    compareAt: 105,
    images: ["/images/products/shoe-2.jpg", "/images/products/shoe-2_1.jpg"],
    rating: 3,
    stock: 21,
    description:
      "Brown derby in tumbled leather with a cushioned footbed and a rubber-tipped sole that handles city pavement.",
    details: ["Tumbled leather", "Cushioned footbed", "Derby lacing"],
    sections: ["trending", "grid"],
    sizes: SHOES,
    colors: ["Brown"],
  },
  {
    _type: "product",
    _id: "pocket-watch-leather-pouch",
    slug: "pocket-watch-leather-pouch",
    title: "Pocket Watch Leather Pouch",
    category: "watches",
    parentCategory: "jewelry",
    price: 150,
    compareAt: 170,
    images: ["/images/products/watch-3.jpg", "/images/products/watch-4.jpg"],
    rating: 3,
    stock: 12,
    description:
      "Mechanical pocket watch with a clear case-back and a vegetable-tanned leather pouch that ages with the piece.",
    details: ["Mechanical movement", "Leather pouch", "Open face"],
    badge: "sale",
    sections: ["top-rated", "grid"],
    colors: ["Silver/brown"],
  },
  {
    _type: "product",
    _id: "silver-deer-heart-necklace",
    slug: "silver-deer-heart-necklace",
    title: "Silver Deer Heart Necklace",
    category: "Jewellery",
    parentCategory: "jewelry",
    price: 84,
    compareAt: 30,
    images: ["/images/products/jewellery-3.jpg"],
    rating: 5,
    stock: 19,
    description:
      "Sterling silver pendant with a deer-and-heart motif on an adjustable cable chain. A small, bright everyday piece.",
    details: ["Sterling silver", "Adjustable chain", "Gift boxed"],
    sections: ["top-rated"],
  },
  {
    _type: "product",
    _id: "titan-100-ml-womens-perfume",
    slug: "titan-100-ml-womens-perfume",
    title: "Titan 100 Ml Womens Perfume",
    category: "Perfume",
    parentCategory: "perfume",
    price: 42,
    compareAt: 10,
    images: ["/images/products/perfume.jpg"],
    rating: 4,
    stock: 55,
    description:
      "A 100ml floral-woody eau de parfum. Opens with citrus, settles into jasmine and warm amber that lasts through the evening.",
    details: ["Eau de parfum", "100 ml", "Floral woody"],
    sections: ["top-rated"],
  },
  {
    _type: "product",
    _id: "mens-leather-reversible-belt",
    slug: "mens-leather-reversible-belt",
    title: "Men's Leather Reversible Belt",
    category: "Belt",
    parentCategory: "clothes",
    price: 24,
    compareAt: 10,
    images: ["/images/products/belt.jpg"],
    rating: 4,
    stock: 70,
    description:
      "Reversible leather belt with a flip buckle — black on one side, brown on the other. One belt, two outfits.",
    details: ["Reversible leather", "Flip buckle", "Cut-to-fit"],
    sections: ["top-rated"],
    sizes: ["32", "34", "36", "38", "40"],
    colors: ["Black/Brown"],
  },
  {
    _type: "product",
    _id: "platinum-zircon-classic-ring",
    slug: "platinum-zircon-classic-ring",
    title: "platinum Zircon Classic Ring",
    category: "jewellery",
    parentCategory: "jewelry",
    price: 62,
    compareAt: 65,
    images: ["/images/products/jewellery-2.jpg"],
    rating: 4,
    stock: 14,
    description:
      "A slim platinum-plated band set with a round zircon. Quiet sparkle that works as a right-hand ring or a stack.",
    details: ["Platinum plated", "Zircon stone", "Gift boxed"],
    sections: ["top-rated"],
    sizes: ["5", "6", "7", "8"],
  },
  {
    _type: "product",
    _id: "smart-watche-vital-plus",
    slug: "smart-watche-vital-plus",
    title: "Smart watche Vital Plus",
    category: "watches",
    parentCategory: "electronics",
    price: 100,
    compareAt: 120,
    images: ["/images/products/watch-1.jpg", "/images/products/watch-2.jpg"],
    rating: 4,
    stock: 40,
    description:
      "Vital Plus smartwatch with heart-rate tracking, sleep scores, and a week of battery. Interchangeable strap, bright always-on display.",
    details: ["7-day battery", "Heart-rate + sleep", "Water resistant"],
    badge: "sale",
    sections: ["top-rated", "grid"],
    colors: ["Black", "Silver"],
  },
  {
    _type: "product",
    _id: "shampoo-conditioner-packs",
    slug: "shampoo-conditioner-packs",
    title: "shampoo, conditioner & facewash packs",
    category: "cosmetics",
    parentCategory: "cosmetics",
    price: 150,
    compareAt: 200,
    images: ["/images/products/shampoo.jpg"],
    rating: 3,
    stock: 40,
    sold: 20,
    available: 40,
    description:
      "A three-piece wash set: clarifying shampoo, weightless conditioner, and a gel face wash. Built for daily use, unscented enough to layer with fragrance.",
    details: ["Shampoo + conditioner + face wash", "Daily formula", "Cruelty free"],
    sections: ["top-rated", "deal"],
  },
  {
    _type: "product",
    _id: "rose-gold-diamonds-earring",
    slug: "rose-gold-diamonds-earring",
    title: "Rose Gold diamonds Earring",
    category: "jewellery",
    parentCategory: "jewelry",
    price: 1990,
    compareAt: 2000,
    images: ["/images/products/jewellery-1.jpg"],
    rating: 3,
    stock: 40,
    sold: 15,
    available: 40,
    description:
      "Rose-gold plated studs set with brilliant-cut stones in a peacock silhouette. A statement pair that still sits close to the ear.",
    details: ["Rose gold plate", "Brilliant-cut stones", "Push back"],
    sections: ["top-rated", "deal"],
  },
  {
    _type: "product",
    _id: "sports-mesh-trainer",
    slug: "sports-mesh-trainer",
    title: "Mesh Court Trainer",
    category: "Sports",
    parentCategory: "footwear",
    price: 44,
    compareAt: 59,
    images: ["/images/products/sports-5.jpg", "/images/products/sports-4.jpg"],
    rating: 4,
    stock: 38,
    description:
      "Low court trainer with a breathable mesh vamp and a gum sole. Weekend shoe that still looks sharp with chinos.",
    details: ["Mesh vamp", "Gum sole", "Padded collar"],
    badge: "sale",
    sections: ["grid"],
    sizes: SHOES,
    colors: ["White/navy"],
  },
  {
    _type: "product",
    _id: "suede-slip-on-loafers",
    slug: "suede-slip-on-loafers",
    title: "Suede Slip-On Loafers",
    category: "Casual",
    parentCategory: "footwear",
    price: 68,
    compareAt: 82,
    images: ["/images/products/shoe-5.jpg"],
    rating: 4,
    stock: 17,
    description:
      "Unlined suede loafers with a flexible rubber sole. Easy on, easy off, and broken in by the second wear.",
    details: ["Unlined suede", "Rubber sole", "Apron toe"],
    badge: "new",
    sections: ["grid"],
    sizes: SHOES,
    colors: ["Taupe"],
  },
];

export const banners: Banner[] = [
  {
    _type: "banner",
    _id: "banner-1",
    kicker: "Trending item",
    title: "Women's latest fashion sale",
    priceLabel: "starting at $ 20.00",
    image: "/images/banner-1.jpg",
    alt: "women's latest fashion sale",
    href: "/shop?category=clothes",
  },
  {
    _type: "banner",
    _id: "banner-2",
    kicker: "Trending accessories",
    title: "Modern sunglasses",
    priceLabel: "starting at $ 15.00",
    image: "/images/banner-2.jpg",
    alt: "modern sunglasses",
    href: "/shop?category=glasses",
  },
  {
    _type: "banner",
    _id: "banner-3",
    kicker: "Sale Offer",
    title: "New fashion summer sale",
    priceLabel: "starting at $ 29.99",
    image: "/images/banner-3.jpg",
    alt: "new fashion summer sale",
    href: "/shop?badge=sale",
  },
];

export const categoryTiles: CategoryTile[] = [
  { _type: "categoryTile", _id: "dress", title: "Dress & frock", slug: "clothes", icon: "/images/icons/dress.svg", count: 53 },
  { _type: "categoryTile", _id: "winter", title: "Winter wear", slug: "clothes", icon: "/images/icons/coat.svg", count: 58 },
  { _type: "categoryTile", _id: "glasses", title: "Glasses & lens", slug: "glasses", icon: "/images/icons/glasses.svg", count: 68 },
  { _type: "categoryTile", _id: "shorts", title: "Shorts & jeans", slug: "clothes", icon: "/images/icons/shorts.svg", count: 84 },
  { _type: "categoryTile", _id: "tee", title: "T-shirts", slug: "clothes", icon: "/images/icons/tee.svg", count: 35 },
  { _type: "categoryTile", _id: "jacket", title: "Jacket", slug: "clothes", icon: "/images/icons/jacket.svg", count: 16 },
  { _type: "categoryTile", _id: "watch", title: "Watch", slug: "electronics", icon: "/images/icons/watch.svg", count: 27 },
  { _type: "categoryTile", _id: "hat", title: "Hat & caps", slug: "clothes", icon: "/images/icons/hat.svg", count: 39 },
];

export const sidebarCategories = [
  {
    title: "Clothes",
    icon: "/images/icons/dress.svg",
    slug: "clothes",
    items: [
      { name: "Shirt", stock: 300, href: "/shop?q=shirt" },
      { name: "shorts & jeans", stock: 60, href: "/shop?q=shorts" },
      { name: "jacket", stock: 50, href: "/shop?q=jacket" },
      { name: "dress & frock", stock: 87, href: "/shop?category=clothes" },
    ],
  },
  {
    title: "Footwear",
    icon: "/images/icons/shoes.svg",
    slug: "footwear",
    items: [
      { name: "Sports", stock: 45, href: "/shop?q=sports" },
      { name: "Formal", stock: 75, href: "/shop?q=formal" },
      { name: "Casual", stock: 35, href: "/shop?q=casual" },
      { name: "Safety Shoes", stock: 26, href: "/shop?category=footwear" },
    ],
  },
  {
    title: "Jewelry",
    icon: "/images/icons/jewelry.svg",
    slug: "jewelry",
    items: [
      { name: "Earrings", stock: 46, href: "/shop?q=earring" },
      { name: "Couple Rings", stock: 73, href: "/shop?q=ring" },
      { name: "Necklace", stock: 61, href: "/shop?q=necklace" },
    ],
  },
  {
    title: "Perfume",
    icon: "/images/icons/perfume.svg",
    slug: "perfume",
    items: [
      { name: "Clothes Perfume", stock: 12, href: "/shop?category=perfume" },
      { name: "Deodorant", stock: 60, href: "/shop?category=perfume" },
      { name: "Jacket", stock: 50, href: "/shop?q=jacket" },
      { name: "Dress & frock", stock: 87, href: "/shop?category=clothes" },
    ],
  },
  {
    title: "Cosmetics",
    icon: "/images/icons/cosmetics.svg",
    slug: "cosmetics",
    items: [
      { name: "Shampoo", stock: 68, href: "/shop?q=shampoo" },
      { name: "Sunscreen", stock: 46, href: "/shop?category=cosmetics" },
      { name: "Body Wash", stock: 79, href: "/shop?category=cosmetics" },
      { name: "Makeup Kit", stock: 23, href: "/shop?category=cosmetics" },
    ],
  },
  {
    title: "Glasses",
    icon: "/images/icons/glasses.svg",
    slug: "glasses",
    items: [
      { name: "Sunglasses", stock: 50, href: "/shop?category=glasses" },
      { name: "Lenses", stock: 48, href: "/shop?category=glasses" },
    ],
  },
  {
    title: "Bags",
    icon: "/images/icons/bag.svg",
    slug: "bags",
    items: [
      { name: "Shopping Bag", stock: 62, href: "/shop?category=bags" },
      { name: "Gym Backpack", stock: 35, href: "/shop?category=bags" },
      { name: "Purse", stock: 80, href: "/shop?category=bags" },
      { name: "Wallet", stock: 75, href: "/shop?category=bags" },
    ],
  },
];

export const megaMenu: NavMegaColumn[] = [
  {
    title: "Electronics",
    href: "/shop?category=electronics",
    links: [
      { label: "Desktop", href: "/shop?category=electronics" },
      { label: "Laptop", href: "/shop?category=electronics" },
      { label: "Camera", href: "/shop?category=electronics" },
      { label: "Tablet", href: "/shop?category=electronics" },
      { label: "Headphone", href: "/shop?category=electronics" },
    ],
    banner: { src: "/images/electronics-banner-1.jpg", alt: "headphone collection" },
  },
  {
    title: "Men's",
    href: "/shop?q=men",
    links: [
      { label: "Formal", href: "/shop?q=formal" },
      { label: "Casual", href: "/shop?q=casual" },
      { label: "Sports", href: "/shop?q=sports" },
      { label: "Jacket", href: "/shop?q=jacket" },
      { label: "Sunglasses", href: "/shop?category=glasses" },
    ],
    banner: { src: "/images/mens-banner.jpg", alt: "men's fashion" },
  },
  {
    title: "Women's",
    href: "/shop?q=women",
    links: [
      { label: "Formal", href: "/shop?category=clothes" },
      { label: "Casual", href: "/shop?category=clothes" },
      { label: "Perfume", href: "/shop?category=perfume" },
      { label: "Cosmetics", href: "/shop?category=cosmetics" },
      { label: "Bags", href: "/shop?category=bags" },
    ],
    banner: { src: "/images/womens-banner.jpg", alt: "women's fashion" },
  },
  {
    title: "Electronics",
    href: "/shop?category=electronics",
    links: [
      { label: "Smart Watch", href: "/shop?q=watch" },
      { label: "Smart TV", href: "/shop?category=electronics" },
      { label: "Keyboard", href: "/shop?category=electronics" },
      { label: "Mouse", href: "/shop?category=electronics" },
      { label: "Microphone", href: "/shop?category=electronics" },
    ],
    banner: { src: "/images/electronics-banner-2.jpg", alt: "mouse collection" },
  },
];

export const mainNav = [
  { label: "Home", href: "/" },
  { label: "Categories", href: "/shop", mega: true },
  { label: "Men's", href: "/shop?q=men" },
  { label: "Women's", href: "/shop?q=women" },
  { label: "Jewelry", href: "/shop?category=jewelry" },
  { label: "Perfume", href: "/shop?category=perfume" },
  { label: "Blog", href: "/blog" },
  { label: "Hot Offers", href: "/shop?badge=sale" },
];

export const mobileNav = [
  {
    label: "Home",
    href: "/",
  },
  {
    label: "Men's",
    href: "/shop?q=men",
    children: [
      { label: "Shirt", href: "/shop?q=shirt" },
      { label: "Shorts & Jeans", href: "/shop?q=shorts" },
      { label: "Safety Shoes", href: "/shop?category=footwear" },
      { label: "Wallet", href: "/shop?category=bags" },
    ],
  },
  {
    label: "Women's",
    href: "/shop?q=women",
    children: [
      { label: "Dress & Frock", href: "/shop?category=clothes" },
      { label: "Earrings", href: "/shop?q=earring" },
      { label: "Necklace", href: "/shop?q=necklace" },
      { label: "Makeup Kit", href: "/shop?category=cosmetics" },
    ],
  },
  {
    label: "Jewelry",
    href: "/shop?category=jewelry",
    children: [
      { label: "Earrings", href: "/shop?q=earring" },
      { label: "Couple Rings", href: "/shop?q=ring" },
      { label: "Necklace", href: "/shop?q=necklace" },
      { label: "Bracelets", href: "/shop?category=jewelry" },
    ],
  },
  {
    label: "Perfume",
    href: "/shop?category=perfume",
    children: [
      { label: "Clothes Perfume", href: "/shop?category=perfume" },
      { label: "Deodorant", href: "/shop?category=perfume" },
      { label: "Flower Fragrance", href: "/shop?category=perfume" },
      { label: "Air Freshener", href: "/shop?category=perfume" },
    ],
  },
  { label: "Blog", href: "/blog" },
  { label: "Hot Offers", href: "/shop?badge=sale" },
];

export const blogPosts: BlogPost[] = [
  {
    _type: "blogPost",
    _id: "clothes-retail-kpis",
    slug: "clothes-retail-kpis-2021-guide",
    title: "Clothes Retail KPIs 2021 Guide for Clothes Executives.",
    category: "Fashion",
    author: "Mr Admin",
    date: "2022-04-06",
    dateLabel: "Apr 06, 2022",
    image: "/images/blog-1.jpg",
    excerpt:
      "The numbers that actually move a fashion floor — sell-through, weeks of supply, and full-price mix — explained for operators, not analysts.",
    body: [
      "Retail fashion still runs on a handful of numbers. Sell-through tells you if the buy was right. Weeks of supply tells you if the next buy should wait. Full-price mix tells you if the brand is healthy or just busy.",
      "This guide walks clothes executives through a practical KPI stack: how to read a week, how to act on a miss, and which vanity metrics to ignore when the floor is loud.",
      "Start with rate of sale by door, not by region. A hero style in three doors can hide a dog in thirty. Then look at size curves — the fastest way markdowns sneak in is an unbalanced XS/XL buy.",
      "Finally, protect the full-price mix. A loud promo week can print revenue and still leave the season underwater. Pair every traffic spike with a margin check before you repeat it.",
    ],
  },
  {
    _type: "blogPost",
    _id: "curbside-fashion-trends",
    slug: "curbside-fashion-trends-pickup",
    title: "Curbside fashion Trends: How to Win the Pickup Battle.",
    category: "Clothes",
    author: "Mr Robin",
    date: "2022-01-18",
    dateLabel: "Jan 18, 2022",
    image: "/images/blog-2.jpg",
    excerpt:
      "Pickup is now a merchandising problem, not just a logistics one. Staging, packaging, and the two-minute handoff decide if the customer comes back.",
    body: [
      "Curbside used to be a pandemic workaround. It is now a service customers compare — and they compare it the way they compare a fitting room: speed, care, and whether the bag looks like it was packed by a person who shops.",
      "Win the pickup battle with a dedicated staging rail, a photo of the packed bag before it leaves, and a two-minute SLA from the 'I'm here' ping.",
      "Fold like the product is being unboxed on a kitchen counter, because it is. Include a return QR on the receipt so the next visit is frictionless.",
    ],
  },
  {
    _type: "blogPost",
    _id: "ebt-vendors-snap",
    slug: "ebt-vendors-snap-online-revenue",
    title: "EBT vendors: Claim Your Share of SNAP Online Revenue.",
    category: "Shoes",
    author: "Mr Selsa",
    date: "2022-02-10",
    dateLabel: "Feb 10, 2022",
    image: "/images/blog-3.jpg",
    excerpt:
      "Online SNAP is a real channel. For vendors already selling essentials, the work is certification, catalog hygiene, and honest delivery windows.",
    body: [
      "SNAP online is no longer experimental. Households that already buy from you in-store will buy from you on the phone if the catalog is certified and the delivery window is honest.",
      "The operational work is unglamorous: eligible SKUs tagged correctly, substitutions that do not surprise, and a pickup path that does not require a second app.",
      "Vendors who treat it as a side door leave money on the table. Treat it as a storefront with its own merchandising rules.",
    ],
  },
  {
    _type: "blogPost",
    _id: "curbside-fashion-pawar",
    slug: "curbside-fashion-trends-pawar",
    title: "Curbside fashion Trends: How to Win the Pickup Battle.",
    category: "Electronics",
    author: "Mr Pawar",
    date: "2022-03-15",
    dateLabel: "Mar 15, 2022",
    image: "/images/blog-4.jpg",
    excerpt:
      "Electronics pickup is unforgiving: serials, seals, and a bag that cannot look opened. Here is the floor playbook.",
    body: [
      "Electronics curbside fails in public. A torn seal, a missing charger, or a five-minute wait with the hazards on — customers remember all three.",
      "Stage high-velocity SKUs in a locked pickup locker. Scan serials into the order before the customer is in the bay. Photograph the closed bag.",
      "The brands that win pickup treat it as a second cash-wrap, not a back-door errand.",
    ],
  },
];

export const services = [
  { icon: "boat", title: "Worldwide Delivery", desc: "For Order Over $100" },
  { icon: "rocket", title: "Next Day delivery", desc: "UK Orders Only" },
  { icon: "headset", title: "Best Online Support", desc: "Hours: 8AM - 11PM" },
  { icon: "undo", title: "Return Policy", desc: "Easy & Free Return" },
  { icon: "ticket", title: "30% money back", desc: "For Order Over $100" },
];

export const footerDirectory = [
  {
    title: "Fashion :",
    links: ["T-shirt", "Shirts", "shorts & jeans", "jacket", "dress & frock", "innerwear", "hosiery"],
  },
  {
    title: "footwear :",
    links: ["sport", "formal", "Boots", "casual", "cowboy shoes", "safety shoes", "Party wear shoes", "Branded", "Firstcopy", "Long shoes"],
  },
  {
    title: "jewellery :",
    links: ["Necklace", "Earrings", "Couple rings", "Pendants", "Crystal", "Bangles", "bracelets", "nosepin", "chain"],
  },
  {
    title: "cosmetics :",
    links: ["Shampoo", "Bodywash", "Facewash", "makeup kit", "liner", "lipstick", "prefume", "Body soap", "scrub", "hair gel", "hair colors", "hair dye", "sunscreen", "skin loson"],
  },
];

export const footerNav = [
  {
    title: "Popular Categories",
    links: [
      { label: "Fashion", href: "/shop?category=clothes" },
      { label: "Electronic", href: "/shop?category=electronics" },
      { label: "Cosmetic", href: "/shop?category=cosmetics" },
      { label: "Health", href: "/shop?category=cosmetics" },
      { label: "Watches", href: "/shop?q=watch" },
    ],
  },
  {
    title: "Products",
    links: [
      { label: "Prices drop", href: "/shop?badge=sale" },
      { label: "New products", href: "/shop?badge=new" },
      { label: "Best sales", href: "/shop?sort=bestsellers" },
      { label: "Contact us", href: "/contact" },
      { label: "Sitemap", href: "/shop" },
    ],
  },
  {
    title: "Our Company",
    links: [
      { label: "Delivery", href: "/about" },
      { label: "Legal Notice", href: "/about" },
      { label: "Terms and conditions", href: "/about" },
      { label: "About us", href: "/about" },
      { label: "Secure payment", href: "/about" },
    ],
  },
  {
    title: "Services",
    links: [
      { label: "Prices drop", href: "/shop?badge=sale" },
      { label: "New products", href: "/shop?badge=new" },
      { label: "Best sales", href: "/shop?sort=bestsellers" },
      { label: "Contact us", href: "/contact" },
      { label: "Sitemap", href: "/shop" },
    ],
  },
];

export const testimonial = {
  name: "Alan Doe",
  role: "CEO & Founder Invision",
  image: "/images/testimonial-1.jpg",
  quote: "Lorem ipsum dolor sit amet consectetur Lorem ipsum dolor dolor sit amet.",
};

const bySlug = new Map(products.map((p) => [p.slug, p]));

export function getProduct(slug: string): Product | undefined {
  return bySlug.get(slug);
}

export function productsIn(section: Product["sections"][number]): Product[] {
  return products.filter((p) => p.sections.includes(section));
}

export function relatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p._id !== product._id && (p.parentCategory === product.parentCategory || p.category === product.category))
    .slice(0, limit);
}

export function searchProducts(query: string): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return products;
  return products.filter((p) =>
    [p.title, p.category, p.parentCategory, p.description].some((v) => v.toLowerCase().includes(q)),
  );
}

export const parentCategories = [
  { slug: "clothes", label: "Clothes" },
  { slug: "footwear", label: "Footwear" },
  { slug: "jewelry", label: "Jewelry" },
  { slug: "perfume", label: "Perfume" },
  { slug: "cosmetics", label: "Cosmetics" },
  { slug: "electronics", label: "Electronics" },
  { slug: "glasses", label: "Glasses" },
  { slug: "bags", label: "Bags" },
] as const;